### ISSUE TITLE
Update logic for aggregating `TypeB` financials

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/fca#7]
## Background
This is an integration between an old Nav accounting system where donation and other financial info is captured and Salesforce, where FCA is now managing all of its projects and budgets. 

There are 2 types of financials --> `TypeA` are mapped directly to Salesforce, but `TypeB` are donations that need to be aggregated and summarized by the Project Number because they don't want to capture these as individual donation line items in Salesforce. 

Currently if the `G_LAccountNo_` is in the range 3100-3599, we aggregate sum Nav financials by `ProjectNr` to output 1 Salesforce `ampi__Financial__c` record per `ProjectNr`. We then hardcode values for `Account_Name__c` and `Account_Number__c`. 
https://github.com/OpenFn/fca/blob/0d2186a0430903fcf4f9515b0bce526f491df30a/fca_bulk_financials.js#L87-L88

## Specific request
For `TypeB` financials, if there are multiple records aggregated --> find the item with the max `G_LAccountNo_`. 
Update the L88 mapping so that... 
```
Account_Number__c: {maxItem.G_LAccountNo_} + ' ' +{maxItem.AccountName}, 
Account_Name__c: 'Donations', 
```

## state
See LP for `FCA Salesforce sandbox`  (THESE CREDS ARE NOT FOR AN UPDATED SANDBOX... so this job might fail... if yes, use `FakeAdaptor` to test locally... and then on OpenFn.org.)

Use: https://github.com/OpenFn/fca/blob/master/sampleTypeB.json
TO TEST, run on OpenFn.org with this message: https://www.openfn.org/projects/1299/messages/9945748

## expression
This change request is specific to the `TypeB` financials logic. 
https://github.com/OpenFn/fca/blob/1117bd80a6b28b8a274fe4994ea6f3532ddeb2bb/fca_bulk_financials.js#L37-L105

## adaptor
`language-salesforce` --> Use `FakeAdaptor` to test locally before on OpenFn.org.

## output
I expect `sampleTypeB.json` to output 2 `ampi__Financial__c` records in Salesforce...
1. Where `"ProjectNr": "61304"` -->  outputs 1 record with `Account_Number__c: '3421 Private Donations'` (because `3421` is the max account no)
2. Where `"ProjectNr": "61304T"` -->outputs 1 record with `Account_Number__c: '3420 Private Donations'`

**Comment by lakhassane** [comment]
@aleksa-krolls this is tested and pushed
